apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-9-deployment
spec:
    replicas: 5
    selector:
      matchLabels:
        app: kiii-9-app
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app: kiii-9-app
      spec:
        containers:
        - name: kiii-9-app
          image: gigo123/kiii-9:2.0
          ports:
          - containerPort: 8080